# vim:filetype=yaml

# ssh://git@git.mokus.io:31613/jorge.costa/test3.git

before_script:
  - apt-get update
  - apt-get install -y make

make_all:
  script:
    - make clean
    - make build
    - make publish
  tags:
    - shell
    - build-as-docker
